# Generated by Django 5.2.8 on 2025-11-22 13:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('original_filename', models.CharField(blank=True, max_length=512)),
                ('domain', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_idx', models.IntegerField()),
                ('section_idx', models.IntegerField(blank=True, null=True)),
                ('section_title', models.CharField(blank=True, max_length=512)),
                ('page_num', models.IntegerField(blank=True, null=True)),
                ('snippet', models.TextField(blank=True)),
                ('pinecone_id', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='rag.uploadeddocument')),
            ],
            options={
                'ordering': ['document', 'chunk_idx'],
            },
        ),
    ]
