# Generated by Django 5.2.8 on 2026-10-04 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0004_conversation_message_delete_conversationmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
