# Generated by Django 5.2.8 on 2026-10-04 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='meta',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
